version: '3.8'

services:
  app:
    container_name: symfony
    image: docker.io/library/symfonix:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - SYMFONY_TYPE=api #optional webapp
    depends_on:
      - database
      
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: